# Types:
# - PLCY - Policy
# - CONT - Contingency
# - MXTR - Mixture

# Available Observation Keys:
# - "target_distance"
# - "target_offset_angle"
# - "del_target_offset_angle"
# - "vel_rot"
# - "vel_frontal"
# - "vel_lateral"
# - "robot_target_distance"
# - "obstacle1_offset_angle"
# - "obstacle1_coverage"
# - "obstacle1_distance"
# - "obstacle2_offset_angle"
# - "obstacle2_coverage"
# - "obstacle2_distance"
# - ...
# - "obstacleN_offset_angle"
# - "obstacleN_coverage"
# - "obstacleN_distance"

# Agent Config Dict Structure:
# - id: <str>
#   - type: <str>
#   - model_type: <str>
#   - observation_keys: <list>
#   - model specific params

name: ppo without distance
reward_indices: [0]
agents:
  - id: 1
    type: PLCY
    model_type: PPO
    observation_keys:
      - target_distance
      - target_offset_angle
      - del_target_offset_angle
      - vel_rot
      - vel_frontal
      - vel_lateral
    reward_indices: [0]
    action_space_dimensionality: 3
    policy_type: MlpPolicy
    learning_rate: 0.001
    verbose: 1
    seed: 14