# Types:
# - PLCY - Policy
# - CONT - Contingency
# - MXTR - Mixture

# Available Observation Keys:
# - "target_distance"
# - "target_offset_angle"
# - "del_target_offset_angle"
# - "vel_rot"
# - "vel_frontal"
# - "vel_lateral"
# - "robot_target_distance"
# - "obstacle1_offset_angle"
# - "obstacle1_coverage"
# - "obstacle1_distance"
# - "obstacle2_offset_angle"
# - "obstacle2_coverage"
# - "obstacle2_distance"
# - ...
# - "obstacleN_offset_angle"
# - "obstacleN_coverage"
# - "obstacleN_distance"

# Agent Config Dict Structure:
# - id: <str>
#   - type: <str>
#   - model_type: <str>
#   - observation_keys: <list>
#     (only if model is learnable)
#   - model specific params

name: handcrafted policy mixture with gaze fixation
reward_indices: [0,2,3]
agents:
  - id: Avoid-1-Obstacle-Agent
    type: PLCY
    model_type: A1O
    action_space_dimensionality: 2

  - id: Avoid-2-Obstacle-Agent
    type: PLCY
    model_type: A2O
    action_space_dimensionality: 2

  - id: Avoid-3-Obstacle-Agent
    type: PLCY
    model_type: A3O
    action_space_dimensionality: 2

  - id: Go-Towards-Target-Agent
    type: PLCY
    model_type: GTT
    action_space_dimensionality: 2

  - id: Mixture-Agent
    type: MXTR
    model_type: PPO
    observation_keys:
      - target_distance
      - target_offset_angle
      - del_target_offset_angle
      - vel_rot
      - vel_frontal
      - vel_lateral
      - robot_target_distance
      #- obstacle1_offset_angle
      - del_obstacle1_distance
      - obstacle1_distance
      #- obstacle2_offset_angle
      - del_obstacle2_distance
      - obstacle2_distance
      #- obstacle3_offset_angle
      - del_obstacle3_distance
      - obstacle3_distance
    action_keys:
      - target_following_relevance
      - obstacle1_evasion_relevance
      - obstacle2_evasion_relevance
      - obstacle3_evasion_relevance
    mixture_mode: 1
    reward_indices: [0,2,3]
    experts: [Avoid-1-Obstacle-Agent, Avoid-2-Obstacle-Agent, Avoid-3-Obstacle-Agent, Go-Towards-Target-Agent]
    policy_type: MlpPolicy
    learning_rate: 0.0001
    verbose: 1
    seed: 130

  - id: Gaze-Fixation-Agent
    type: CONT
    model_type: GFM
    contingent_agent: Mixture-Agent