# Types:
# - PLCY - Policy
# - CONT - Contingency
# - MXTR - Mixture

# Available Observation Keys:
# - "target_distance"
# - "target_offset_angle"
# - "del_target_offset_angle"
# - "vel_rot"
# - "vel_frontal"
# - "vel_lateral"
# - "robot_target_distance"
# - "obstacle1_offset_angle"
# - "obstacle1_coverage"
# - "obstacle1_distance"
# - "obstacle2_offset_angle"
# - "obstacle2_coverage"
# - "obstacle2_distance"
# - ...
# - "obstacleN_offset_angle"
# - "obstacleN_coverage"
# - "obstacleN_distance"

# Agent Config Dict Structure:
# - id: <str>
#   - type: <str>
#   - model_type: <str>
#   - observation_keys: <list>
#     (only if model is learnable)
#   - model specific params

random_seed: 2
agents:
  - id: 1
    type: PLCY
    model_type: ANO
    action_space_dimensionality: 2

  - id: 2
    type: PLCY
    model_type: GTT
    action_space_dimensionality: 2

  - id: 3
    type: MX2R
    model_type: TOM
    mixture_mode: 2
    experts: [1, 2]

  - id: 4
    type: CONT
    model_type: GFM
    contingent_agent: 3