name: monolithic ppo with gaze fixation
agents:
  - id: Translational-Movement-Agent
    type: PLCY
    model_type: PPO
    reward_indices: [0,1,2,3,4]
    observation_keys:
      # - target_distance
      # - target_offset_angle
      # - del_target_offset_angle
      - robot_target_distance
      - obstacle1_distance
      - obstacle1_offset_angle
      # - vel_rot
      # - vel_frontal
      # - vel_lateral
    action_keys:
      - "frontal_movement"
      - "lateral_movement"
    action_space_dimensionality: 2
    policy_type: MlpPolicy
    learning_rate: 0.0003
    verbose: 1
    seed: 1

  - id: 2
    type: CONT
    model_type: GFM
    contingent_agent: Translational-Movement-Agent