random_seed: 140
name: monolithic ppo with gaze fixation
agents:
  - id: 1
    type: PLCY
    model_type: PPO
    observation_keys:
      - target_distance
      - target_offset_angle
      - del_target_offset_angle
      - robot_target_distance
      - vel_rot
      - vel_frontal
      - vel_lateral
    action_space_dimensionality: 2
    policy_type: MlpPolicy
    learning_rate: 0.001
    verbose: 1
    seed: 14

  - id: 2
    type: CONT
    model_type: GFM
    contingent_agent: 1