# Types:
# - PLCY - Policy
# - CONT - Contingency
# - MXTR - Mixture

# Available Observation Keys:
# - "target_distance"
# - "target_offset_angle"
# - "del_target_offset_angle"
# - "vel_rot"
# - "vel_frontal"
# - "vel_lateral"
# - "robot_target_distance"
# - "obstacle1_offset_angle"
# - "obstacle1_coverage"
# - "obstacle1_distance"
# - "obstacle2_offset_angle"
# - "obstacle2_coverage"
# - "obstacle2_distance"
# - ...
# - "obstacleN_offset_angle"
# - "obstacleN_coverage"
# - "obstacleN_distance"

# Reward Indices:
# - 0 - target proximity reward
# - 1 - time penalty
# - 2 - obstacle proximity penalty
# - 3 - energy waste penalty
# - 4 - collision penalty

# Agent Config Dict Structure:
# - id: <str>
#   - type: <str>
#   - model_type: <str>
#   - observation_keys: <list>
#     (only if model is learnable)
#   - reward_indices: <list>
#   - model specific params

name: ppo policy mixture with gaze fixation
agents:
  - id: Go-Towards-Target
    type: PLCY
    model_type: GTT

  - id: Avoid-Nearest-Obstacle
    type: PLCY
    model_type: ANO

  - id: Go-Left
    type: PLCY
    model_type: GLM

  - id: Gaze-Fixation
    type: PLCY
    model_type: NGFM

  - id: Mixture
    type: MXTR
    model_type: PPO
    observation_keys:
      - robot_target_distance
      - obstacle1_distance
      - obstacle1_offset_angle
    action_keys:
      - "frontal_movement"
      - "lateral_movement"
      - "rotational_movement"
    reward_indices: [0]
    mixture_mode: 1
    experts: [Go-Towards-Target, Avoid-Nearest-Obstacle, Go-Left, Gaze-Fixation]
    policy_type: MlpPolicy
    learning_rate: 0.0003
    verbose: 1
    seed: 10
